#登陆相关配置
login:
  #开放的模拟登陆api服务器地址
  api: "http://www.zimo.wiki:8080/wisedu-unified-login-api-v1.0/api/login"
#用户组配置
users:
  #单个用户配置
  - user:
      #username 学号或者工号或身份证号
      username: "123456789"
      #password 密码
      password: "123456789"
      #address 地址，定位信息  中国河南省xx市xx区xx路
      address: 中国河南省xx市xx路/村
      #email 接受通知消息的邮箱
      email: xx@xx.com
      #school 学校全称
      school: 长春师范大学
      #lon 经度 保留六位小数
      lon: "123.123456"
      #lat 纬度 保留六位小数
      lat: "123.123456"
      #abnormalReason 反馈信息 无需修改
      abnormalReason:
      #photo 签到照片，不需要可不填，或者直接删除
#      photo: default.png
#多用户配置，将下面的注释去掉即可，如果有表单内容有图片，不建议使用多用户配置
#今日校园相关配置
cpdaily:
  check: true
  defaults:
    - default:
        title: 今天你的体温是多少？
        value: 36.6℃
    - default:
        title: 你当前的状态是？
        value: 正常
    - default:
        title: 你当前的身体健康状况?
        value: 无症状
    - default:
        title: 近14天是否接触过新冠肺炎确诊病例/疑似病例/无症状感染者？
        value: 否
    - default:
        title: 是否途径/逗留/身处疫情中高风险地区？
        value: 否
