#登陆相关配置
login:
  #开放的模拟登陆api服务器地址
  api: "http://www.zimo.wiki:8080/wisedu-unified-login-api-v1.0/api/login"
#用户组配置
users:
  #单个用户配置
  - user:
      #username 学号或者工号
      username: '161105024'
      #password 密码
      password: '161105024'
      #address 地址，定位信息  中国河南省xx市xx区xx路
      address: 中国河南省
      #email 接受通知消息的邮箱
      email: 461009747@qq.com
      #school 学校全称
      school: 新乡医学院
      #lon 经度
      lon: '114.639377'
      #lat 纬度
      lat: '32.958833'
      #abnormalReason 反馈信息
      abnormalReason: 在家
      #photo 签到照片，不需要可不填，或者直接删除
      photo: default.png
  #多用户配置，将下面的注释去掉即可，如果有表单内容有图片，不建议使用多用户配置
#今日校园相关配置
cpdaily:
  #是否检查问题,true检查，false不检查
  check: false
  #附加信息组默认选项配置，没有可留空
  defaults:
  #附加信息组默认选项配置，按顺序，可留空
  #    - default:
  #        #表单项标题
  #        title: 体温
  #        #表单项默认值
  #        value: 正常
  #多个额外选项配置
#    - default:
#        #表单项标题
#        title: 体温
#        #表单项默认值
#        value: 正常
